server:
  port: 60001
spring:
  application:
    name: micro-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
# jwt配置
jwt:
  # 密钥
  key: micro
  # 过期时间（秒）
  expireTime: 7200
  # 校验时间（毫秒）
  validateTime: 300000