server:
  port: 60001
spring:
  application:
    name: micro-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
micro:
  # 网关配置
  gateway:
    whitelist:
      - /login
  # jwt配置
  jwt:
    # 密钥
    key: micro
    # 过期时间（秒）
    expireTime: 7200
    # 校验时间（毫秒）
    validateTime: 300000