server:
  port: 60001
spring:
  application:
    name: micro-gateway
  redis:
    host: localhost
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: login
          uri: lb://micro-system
          predicates:
            - Path=/login
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
micro:
  # 网关配置
  gateway:
    whitelist:
      - /login
  login:
    expire-time: 30
