spring:
  application:
    name: micro-dict
  redis:
    host: localhost
    password: 123456
  rabbitmq:
    host: localhost
    password: 123456
    username: admin
    port: 5672
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/micro_dict?serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 60004
logging:
  level:
    com.alibaba.nacos.client.config.impl: WARN
groot:
  # 登录拦截器是否开启
  login-interceptor: false
  swagger:
    base-package: com.micro
  rabbit-mq:
    exchange-name: single-blog
    queue-name: single-blog
    routing-key: single-blog